apiVersion: apps/v1
kind: Deployment
metadata:
  name: MLOpsAssignment2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MLOpsAssignment2
  template:
    metadata:
      labels:
        app: MLOpsAssignment2
    spec:
      containers:
      - name: MLOpsAssignment2
        image: cseniteshkumar/mlopsassignment2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"